use std::path::{Path, PathBuf};

/// Embed the built frontend into the binary.
///
/// The gateway (src/web.rs) serves the SAME files Tauri loads, so they have to
/// live inside the executable — a `.app` you hand a teammate can't depend on a
/// `dist/` folder sitting next to it. Vite's filenames are content-hashed, so
/// this walks the directory at compile time and generates a lookup table rather
/// than `include_str!`-ing names that change every build.
///
/// A missing `dist/` is not an error: `cargo test` and a bare `cargo build`
/// should still work. The table comes out empty and the gateway serves a page
/// that says "run npm run build", which beats failing the whole compile.
fn main() {
    let ui = PathBuf::from("../ui-react/dist");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let mut entries: Vec<(String, PathBuf)> = Vec::new();

    if ui.is_dir() {
        walk(&ui, &ui, &mut entries);
        entries.sort();
    } else {
        println!(
            "cargo:warning=no built frontend at {} — run `npm run build` in desktop/ui-react (the gateway will say so too)",
            ui.display()
        );
    }

    // Rebuild when the frontend does. Watching the directory catches new files;
    // watching each file catches edits to existing ones.
    println!("cargo:rerun-if-changed=../ui-react/dist");
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let mut code = String::from(
        "// Generated by build.rs — the built frontend, embedded.\n\
         pub static UI_FILES: &[(&str, &[u8], &str)] = &[\n",
    );
    for (route, path) in &entries {
        let abs = std::fs::canonicalize(path).unwrap_or_else(|_| path.clone());
        code.push_str(&format!(
            "    ({:?}, include_bytes!({:?}), {:?}),\n",
            route,
            abs,
            mime_for(path)
        ));
    }
    code.push_str("];\n");

    std::fs::write(out.join("ui_assets.rs"), code).expect("write ui_assets.rs");
    tauri_build::build()
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            walk(base, &p, out);
            continue;
        }
        let Ok(rel) = p.strip_prefix(base) else { continue };
        // Routes are what a browser asks for: "/app.abc123.js".
        let route = format!("/{}", rel.to_string_lossy().replace('\\', "/"));
        out.push((route, p));
    }
}

fn mime_for(p: &Path) -> &'static str {
    match p.extension().and_then(|e| e.to_str()).unwrap_or("") {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "ttf" => "font/ttf",
        _ => "application/octet-stream",
    }
}
